{% set name = "discretisedfield" %}
{% set version = "0.92.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('_', '-') }}-{{ version }}.tar.gz
  sha256: c540ff2c68bf24555fbaca64cadc1d383f447f6510740aac400c887cb7526588

build:
  noarch: python
  number: 0
  entry_points:
    - ovf2vtk = discretisedfield.io.ovf2vtk:ovf2vtk
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - ubermagutil >=0.64.0
    - matplotlib-base >=3.3, !=3.7.2
    - k3d >=2.11
    - pandas >=1.1
    - h5py >=3.1
    - jinja2
    - scipy >=1.6
    - vtk >=9.1
    - xarray
    - holoviews
    - sympy >=1.10.1
    - pyvista[all] >=0.42.3

test:
  requires:
    - python {{ python_min }}
  imports:
    - discretisedfield
  commands:
    - ovf2vtk -h
    - pytest -v -m "not pyvista" $(python -c "from pathlib import Path; import discretisedfield.tests; print(Path(discretisedfield.tests.__file__).parent)")

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python package for the analysis and visualisation of finite difference fields.
  doc_url: https://ubermag.github.io/documentation/discretisedfield.html
  dev_url: https://github.com/ubermag/discretisedfield

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
    - lang-m
    - samjrholt
    - swapneelap
