{% set name = "discretisedfield" %}
{% set version = "0.65.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('_', '-') }}-{{ version }}.tar.gz
  sha256: ee78a049672371289c7bc45f7959819923e10412fb585fc567c8503c0daea5ea

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - ubermagutil >=0.63.0
    - matplotlib-base >=3.3
    - jupyterlab >=3.0,<4
    - k3d >=2.11
    - pandas >=1.1
    - h5py >=3.1
    - jinja2
    - scipy >=1.6
    - vtk
    - xarray
    - hvplot

test:
  imports:
    - discretisedfield
  commands:
    - python -c "import sys; import discretisedfield as df; sys.exit(df.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python package for the analysis and visualisation of finite difference fields.
  doc_url: https://ubermag.github.io/documentation/discretisedfield.html
  dev_url: https://github.com/ubermag/discretisedfield

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
    - lang-m
    - samjrholt
    - swapneelap
