{% set version = "0.8.4" %}
{% set name = "discretisedfield" %}
{% set sha256 = "91760ef56cfed70954f1d34ab4a7b60165a8348d02449fc79070c1f96796b35c" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: pip install --no-deps .

requirements:
  build:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - numpy 
    - matplotlib
    - pyvtk
    - ubermagutil
    - pytest

test:
  imports:
    - discretisedfield
    - discretisedfield.util
    
  commands:
    - python -c "import sys; import discretisedfield as m; sys.exit(m.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-clause
  license_family: BSD
  license_file: LICENSE
  summary: Python package for defining, reading, analysis, and plotting of finite difference fields.
  doc_url: http://discretisedfield.readthedocs.io
  dev_url: https://github.com/ubermag/discretisedfield

  description: |
    discretisedfield provides a class to represent (finite difference)
    discretisation of a field (in the continuum field theory context).

    It is part of the Ubermag project (https://github.com/ubermag
    and http://ubermag.github.io).

extra:
  recipe-maintainers:
    - fangohr
    - marijanbeg
    - takluyver
    - davidcortesortuno
    - rpep
