{% set name = "discretisedfield" %}
{% set version = "0.60.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('_', '-') }}-{{ version }}.tar.gz
  sha256: 74282a3d63d56d5937672710ad6db054c042bcfb136c71c3ff9f0beaee508a9a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - ubermagutil ==0.4.1
    - matplotlib-base >=3.3
    - jupyterlab ==2.2
    - k3d ==2.9
    - pandas >=1.1
    - h5py
    - scipy >=1.5

test:
  imports:
    - discretisedfield
  commands:
    - python -c "import sys; import discretisedfield as df; sys.exit(df.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python package for the analysis and visualisation of finite difference fields.
  doc_url: http://discretisedfield.readthedocs.io
  dev_url: https://github.com/ubermag/discretisedfield

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
    - lang-m
