{% set name = "discretisedfield" %}
{% set version = "0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4bac00ce55fde5beaa0dd064d692b9e39cdd29fd297d30666be385182dc65290

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - ubermagutil ==0.3
    - matplotlib-base >=3.3
    - jupyterlab ==2.2
    - k3d ==2.9
    - pandas >=1.2
    - h5py

test:
  imports:
    - discretisedfield
  commands:
    - python -c "import sys; import discretisedfield as df; sys.exit(df.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python package for the analysis and visualisation of finite difference fields.
  doc_url: http://discretisedfield.readthedocs.io
  dev_url: https://github.com/ubermag/discretisedfield

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
    - lang-m
