{% set version = "0.8.1" %}
{% set name = "discretisedfield" %}
{% set sha256 = "8789ddadc2eb454b1bc344fffe2372bab71a2d1400a1152b22e97412c91398fc" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: True  # [py27]
  number: 0
  script: pip install --no-deps .

requirements:
  build:
    - python
    - pip

  run:
    - python
    - numpy  >=1.11 
    - matplotlib
    - pyvtk
    - joommfutil
    - pytest
    - hypothesis

test:
  imports:
    - discretisedfield
    - discretisedfield.util
    - discretisedfield.mesh
    
  commands:
    - python -c "import discretisedfield; discretisedfield.test()"

about:
  home: http://joommf.github.io/
  license: BSD 3-clause
  license_family: BSD
  license_file: LICENSE
  summary: Reading and analysing OOMMF odt files
  doc_url: http://discretisedfield.readthedocs.io
  dev_url: https://github.com/joommf/discretisedfield

  description: |
    discretisedfield provides a class to represent (finite difference)
    discretisation of a field (in the continuum field theory context).

    It is part of the Jupyter-OOMMF project (https://github.com/joommf
    and http://joommf.github.io).

extra:
  recipe-maintainers:
    - fangohr
    - marijanbeg
    - takluyver
    - davidcortesortuno
    - rpep
