{% set version = "0.8.3" %}
{% set name = "discretisedfield" %}
{% set sha256 = "42f2fa88b72e29ca30d8c5112a3c10cc2dcbda57d95014242e42f5ad277d098f" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: pip install --no-deps .

requirements:
  build:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - numpy  >=1.11 
    - matplotlib
    - pyvtk
    - joommfutil
    - pytest

test:
  imports:
    - discretisedfield
    - discretisedfield.util
    - discretisedfield.mesh
    
  commands:
    - python -c "import sys; import discretisedfield as m; sys.exit(m.test())"

about:
  home: http://joommf.github.io/
  license: BSD 3-clause
  license_family: BSD
  license_file: LICENSE
  summary: Reading and analysing OOMMF odt files
  doc_url: http://discretisedfield.readthedocs.io
  dev_url: https://github.com/joommf/discretisedfield

  description: |
    discretisedfield provides a class to represent (finite difference)
    discretisation of a field (in the continuum field theory context).

    It is part of the Jupyter-OOMMF project (https://github.com/joommf
    and http://joommf.github.io).

extra:
  recipe-maintainers:
    - fangohr
    - marijanbeg
    - takluyver
    - davidcortesortuno
    - rpep
