{% set name = "discretisedfield" %}
{% set version = "0.8.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ed5692df8395d0a1a635b02115c48d30cf4dfc88674500cd399eeb517aaa535e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - ubermagutil ==0.2.7
    - matplotlib-base >=3.3
    - pandas
    - jupyterlab ==2.2
    - h5py
    - k3d ==2.9

test:
  imports:
    - discretisedfield
  commands:
    - python -c "import sys; import discretisedfield as df; sys.exit(df.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python package for the analysis and visualisation of finite difference fields.
  doc_url: http://discretisedfield.readthedocs.io
  dev_url: https://github.com/ubermag/discretisedfield

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
    - lang-m
