{% set name = "discretisedfield" %}
{% set version = "0.8.13" %}
{% set sha256 = "3a523f97cbe157247ae1e1176f3b4503259555c511c07d0ea7a7aaad3eaf9d66" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - ubermagutil ==0.2.6
    - matplotlib-base >=3.2
    - pandas >=1.0
    - jupyterlab >=2.1
    - h5py >=2.10
    - k3d >=2.8

test:
  imports:
    - discretisedfield
  commands:
    - python -c "import sys; import discretisedfield as df; sys.exit(df.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python package for the analysis and visualisation of finite difference fields.
  doc_url: http://discretisedfield.readthedocs.io
  dev_url: https://github.com/ubermag/discretisedfield

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
