{% set version = "0.8.5" %}
{% set name = "discretisedfield" %}
{% set sha256 = "0dfd7d2714f6a00a715fb5c797b11f63437665784b35cb27a6c92a790eb4c050" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: pip install --no-deps . -vvv

requirements:
  build:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - numpy 
    - matplotlib
    - pyvtk
    - ubermagutil
    - k3d
    - pytest

test:
  imports:
    - discretisedfield
    - discretisedfield.util
  commands:
    - python -c "import sys; import discretisedfield as m; sys.exit(m.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-clause
  license_family: BSD
  license_file: LICENSE
  summary: Python package for definition, reading, and visualisation of finite difference fields.
  doc_url: http://discretisedfield.readthedocs.io
  dev_url: https://github.com/ubermag/discretisedfield

  description: |
    This Python package provides:

        - Definition of finite difference meshes and fields
        - Reading and writing of different file types, such as `.ovf` and `.vtk`
        - Visualisation of finite difference meshes and fields using `matplotlib` and `k3d`

    It is available on all major operating systems (Windows, MacOS, Linux) and requires Python 3.6 or higher.

extra:
  recipe-maintainers:
    - fangohr
    - marijanbeg
    - takluyver
    - davidcortesortuno
    - rpep
