{% set name = "discretisedfield" %}
{% set version = "0.91.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('_', '-') }}-{{ version }}.tar.gz
  sha256: 895a1efa4045a6973ef2a1a326dec4db2aa6a40b52d3af4927cc2f2f3541450b

build:
  noarch: python
  number: 0
  entry_points:
    - ovf2vtk = discretisedfield.io.ovf2vtk:ovf2vtk
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - ubermagutil >=0.63.4
    - matplotlib-base >=3.3, !=3.7.2
    - k3d >=2.11
    - pandas >=1.1
    - h5py >=3.1
    - jinja2
    - scipy >=1.6
    - vtk >=9.1
    - xarray
    - holoviews
    - sympy >=1.10.1
    - pyvista[all] >=0.42.3

test:
  imports:
    - discretisedfield
  commands:
    - ovf2vtk -h
    - python -c "import sys; import discretisedfield as df; sys.exit(df.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python package for the analysis and visualisation of finite difference fields.
  doc_url: https://ubermag.github.io/documentation/discretisedfield.html
  dev_url: https://github.com/ubermag/discretisedfield

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
    - lang-m
    - samjrholt
    - swapneelap
