{% set version = "0.8.9" %}
{% set name = "discretisedfield" %}
{% set sha256 = "c13767a1093779d4550c0ba2ccabb52d027a9fef937c538435a729c3c13c9c6e" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: pip install --no-deps . -vvv

requirements:
  build:
    - python >=3.7
    - pip

  run:
    - python >=3.7
    - ubermagutil
    - matplotlib-base
    - jupyterlab
    - seaborn
    - h5py
    - pyvtk
    - k3d

test:
  imports:
    - discretisedfield
    - discretisedfield.util
  commands:
    - python -c "import sys; import discretisedfield as df; sys.exit(df.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-clause
  license_family: BSD
  license_file: LICENSE
  summary: Python package for the analysis and visualisation of finite difference fields.
  doc_url: http://discretisedfield.readthedocs.io
  dev_url: https://github.com/ubermag/discretisedfield

  description: |
    `discretisedfield` is a Python package that provides:
      - definition of finite difference regions, meshes, and fields,
      - analysis of finite difference fields,
      - reading and writing of different file types (OVF, VTK, and HDF5), and
      - visualisation using matplotlib and k3d.

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
