travis:
  secure:
    BINSTAR_TOKEN: cCrUULfSwCS7vZ4foFDDrCR4j7yvEaPwvHdTJcUZk8O9IIUmEGiym3kb71LoCPmQ0InSMJ5H48tFsv1Awmnrideld/Uh3vz5F64YXNPMlOfdXiq44/b4Fr/aQ5e931FdbUIxC7oc8vbI4QhsSMSsX8uKW1nPuAwd8ErlsVUqGWk/8J6yFIqhTzNymeftIZ552n125+OO0Vw4OBog+W9Kkikl4DEKHDBAum3bbb5vqMkTW1lAQSTjwngIeG61r14+4yAu3/wgp3IWxv62t9M7fwJ7gtL8oZeU88IECXSMuV+S+AIG5pC71L/RgFdQ9dZnYCsK8bERPhlLYhxMEYzEemQHB2wUdp+BEV35ylScCTBOX9DQseR2582FJqmBR6wHv3FSe2mNMJ5tgc8Nvf2lIGRvUmI7v6+VMAKb8t+SXOA0SBKE2haJF9NpCJwE8mUDzyK0p/C+y+TQEL2Bf+I18ZtChs6tvMdx47yijyVbSHExnJQdus+zeDJEesuf5CfY8jRFvTeIuRu+1s06BiwV87TjeG/nRtaQCMXUCoRK9tQCxGe3EN0zVzOJBa3aC1QQ+xJm0mJYwOe+QHUtabqCErbOnv7rvh+jBIS14o1Q2itugyAB3GRfN5H/U7bxgXFtEF9ctqNoBU3/S459dKjNHq6W8VzDDyJvGM+CeC1vX68=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
