travis:
  secure:
    BINSTAR_TOKEN: 1goCkVNgIw4rcVH4UDIHZsj7Y+3lQbtwWCkk/jyDmHWJzw4PkVL6kWAddKYn0D/s6KE8yeXasZ8Zfv1knKL31asTXkRhthzo6mwunjsvwxxjvsOQI3l5M54hVM/a8skF+HmNo1QjeHySfXV/YLg7Ey4mRCaw2J0XX00xbdxFUza3t00NamTpo6f7fBwNs45cwKbp+YoS4xAzLk13k4hqSwFQPqPf0iSkBC9aJO7BVjSmPFxTOD+0/e7cCb7aC4ICHbxaejET6wbVpzvatLmc8h02ffzJMTSWF+2X8FxRIK5SlaMSUCCvQFJGpCN/9Z5wr6PchDQG1uPWCAWuBe6FkW5tsLN0Bpsc4T3ZXuwYK+ELOVZE5U9lq6QLnPWXAyjFmywtXREioj+1WVsHOiIveYwGx9Ht6I8Kmy/LrrJI3k2NdorH1ozOjm1zmmLq5LLj4ykoXlFivuiBw59W9uVQiKQeMn1FaLls7gHWYkCbDp5DOaiP88yvO7AGf+EeGzIz5MxZmgFoDQBUhbD4v8m4Ln+Utm4xrbHsvmPL/YQSfKnDZq91oYck8P4J44cInmCs9ycOXILr2CxWGLtnBQZL9LoqqwHP54PXpenZ7aRAvbKXizDiOF05jS8/vsNBDEpPvnZYA5oeQo2zT6eiJLcnlU9g0r0xEjlF8aRNXKxg/AY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
